
ORP = {
	'Praha': {'orp_kod': 1000, 'kraj_kod': 3018, 'kraj_nazev': 'Hlavní město Praha'},
	'Benešov': {'orp_kod': 2101, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Beroun': {'orp_kod': 2102, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Brandýs nad Labem-Stará Boleslav': {'orp_kod': 2103, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Čáslav': {'orp_kod': 2104, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Černošice': {'orp_kod': 2105, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Český Brod': {'orp_kod': 2106, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Dobříš': {'orp_kod': 2107, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Hořovice': {'orp_kod': 2108, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Kladno': {'orp_kod': 2109, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Kolín': {'orp_kod': 2110, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Kralupy nad Vltavou': {'orp_kod': 2111, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Kutná Hora': {'orp_kod': 2112, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Lysá nad Labem': {'orp_kod': 2113, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Mělník': {'orp_kod': 2114, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Mladá Boleslav': {'orp_kod': 2115, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Mnichovo Hradiště': {'orp_kod': 2116, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Neratovice': {'orp_kod': 2117, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Nymburk': {'orp_kod': 2118, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Poděbrady': {'orp_kod': 2119, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Příbram': {'orp_kod': 2120, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Rakovník': {'orp_kod': 2121, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Říčany': {'orp_kod': 2122, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Sedlčany': {'orp_kod': 2123, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Slaný': {'orp_kod': 2124, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Vlašim': {'orp_kod': 2125, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Votice': {'orp_kod': 2126, 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	'Blatná': {'orp_kod': 3101, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'České Budějovice': {'orp_kod': 3102, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Český Krumlov': {'orp_kod': 3103, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Dačice': {'orp_kod': 3104, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Jindřichův Hradec': {'orp_kod': 3105, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Kaplice': {'orp_kod': 3106, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Milevsko': {'orp_kod': 3107, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Písek': {'orp_kod': 3108, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Prachatice': {'orp_kod': 3109, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Soběslav': {'orp_kod': 3110, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Strakonice': {'orp_kod': 3111, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Tábor': {'orp_kod': 3112, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Trhové Sviny': {'orp_kod': 3113, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Třeboň': {'orp_kod': 3114, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Týn nad Vltavou': {'orp_kod': 3115, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Vimperk': {'orp_kod': 3116, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Vodňany': {'orp_kod': 3117, 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	'Blovice': {'orp_kod': 3201, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Domažlice': {'orp_kod': 3202, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Horažďovice': {'orp_kod': 3203, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Horšovský Týn': {'orp_kod': 3204, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Klatovy': {'orp_kod': 3205, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Kralovice': {'orp_kod': 3206, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Nepomuk': {'orp_kod': 3207, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Nýřany': {'orp_kod': 3208, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Plzeň': {'orp_kod': 3209, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Přeštice': {'orp_kod': 3210, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Rokycany': {'orp_kod': 3211, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Stod': {'orp_kod': 3212, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Stříbro': {'orp_kod': 3213, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Sušice': {'orp_kod': 3214, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Tachov': {'orp_kod': 3215, 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	'Aš': {'orp_kod': 4101, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Cheb': {'orp_kod': 4102, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Karlovy Vary': {'orp_kod': 4103, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Kraslice': {'orp_kod': 4104, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Mariánské Lázně': {'orp_kod': 4105, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Ostrov': {'orp_kod': 4106, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Sokolov': {'orp_kod': 4107, 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	'Bílina': {'orp_kod': 4201, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Děčín': {'orp_kod': 4202, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Chomutov': {'orp_kod': 4203, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Kadaň': {'orp_kod': 4204, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Litoměřice': {'orp_kod': 4205, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Litvínov': {'orp_kod': 4206, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Louny': {'orp_kod': 4207, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Lovosice': {'orp_kod': 4208, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Most': {'orp_kod': 4209, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Podbořany': {'orp_kod': 4210, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Roudnice nad Labem': {'orp_kod': 4211, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Rumburk': {'orp_kod': 4212, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Teplice': {'orp_kod': 4213, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Ústí nad Labem': {'orp_kod': 4214, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Varnsdorf': {'orp_kod': 4215, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Žatec': {'orp_kod': 4216, 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	'Česká Lípa': {'orp_kod': 5101, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Frýdlant': {'orp_kod': 5102, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Jablonec nad Nisou': {'orp_kod': 5103, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Jilemnice': {'orp_kod': 5104, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Liberec': {'orp_kod': 5105, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Nový Bor': {'orp_kod': 5106, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Semily': {'orp_kod': 5107, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Tanvald': {'orp_kod': 5108, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Turnov': {'orp_kod': 5109, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Železný Brod': {'orp_kod': 5110, 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	'Broumov': {'orp_kod': 5201, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Dobruška': {'orp_kod': 5202, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Dvůr Králové nad Labem': {'orp_kod': 5203, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Hořice': {'orp_kod': 5204, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Hradec Králové': {'orp_kod': 5205, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Jaroměř': {'orp_kod': 5206, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Jičín': {'orp_kod': 5207, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Kostelec nad Orlicí': {'orp_kod': 5208, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Náchod': {'orp_kod': 5209, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Nová Paka': {'orp_kod': 5210, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Nové Město nad Metují': {'orp_kod': 5211, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Nový Bydžov': {'orp_kod': 5212, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Rychnov nad Kněžnou': {'orp_kod': 5213, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Trutnov': {'orp_kod': 5214, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Vrchlabí': {'orp_kod': 5215, 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	'Česká Třebová': {'orp_kod': 5301, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Hlinsko': {'orp_kod': 5302, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Holice': {'orp_kod': 5303, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Chrudim': {'orp_kod': 5304, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Králíky': {'orp_kod': 5305, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Lanškroun': {'orp_kod': 5306, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Litomyšl': {'orp_kod': 5307, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Moravská Třebová': {'orp_kod': 5308, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Pardubice': {'orp_kod': 5309, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Polička': {'orp_kod': 5310, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Přelouč': {'orp_kod': 5311, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Svitavy': {'orp_kod': 5312, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Ústí nad Orlicí': {'orp_kod': 5313, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Vysoké Mýto': {'orp_kod': 5314, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Žamberk': {'orp_kod': 5315, 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	'Bystřice nad Pernštejnem': {'orp_kod': 6101, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Havlíčkův Brod': {'orp_kod': 6102, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Humpolec': {'orp_kod': 6103, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Chotěboř': {'orp_kod': 6104, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Jihlava': {'orp_kod': 6105, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Moravské Budějovice': {'orp_kod': 6106, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Náměšť nad Oslavou': {'orp_kod': 6107, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Nové Město na Moravě': {'orp_kod': 6108, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Pacov': {'orp_kod': 6109, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Pelhřimov': {'orp_kod': 6110, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Světlá nad Sázavou': {'orp_kod': 6111, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Telč': {'orp_kod': 6112, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Třebíč': {'orp_kod': 6113, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Velké Meziříčí': {'orp_kod': 6114, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Žďár nad Sázavou': {'orp_kod': 6115, 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	'Blansko': {'orp_kod': 6201, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Boskovice': {'orp_kod': 6202, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Brno': {'orp_kod': 6203, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Břeclav': {'orp_kod': 6204, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Bučovice': {'orp_kod': 6205, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Hodonín': {'orp_kod': 6206, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Hustopeče': {'orp_kod': 6207, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Ivančice': {'orp_kod': 6208, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Kuřim': {'orp_kod': 6209, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Kyjov': {'orp_kod': 6210, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Mikulov': {'orp_kod': 6211, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Moravský Krumlov': {'orp_kod': 6212, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Pohořelice': {'orp_kod': 6213, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Rosice': {'orp_kod': 6214, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Slavkov u Brna': {'orp_kod': 6215, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Šlapanice': {'orp_kod': 6216, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Tišnov': {'orp_kod': 6217, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Veselí nad Moravou': {'orp_kod': 6218, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Vyškov': {'orp_kod': 6219, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Znojmo': {'orp_kod': 6220, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Židlochovice': {'orp_kod': 6221, 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	'Hranice': {'orp_kod': 7101, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Jeseník': {'orp_kod': 7102, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Konice': {'orp_kod': 7103, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Lipník nad Bečvou': {'orp_kod': 7104, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Litovel': {'orp_kod': 7105, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Mohelnice': {'orp_kod': 7106, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Olomouc': {'orp_kod': 7107, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Prostějov': {'orp_kod': 7108, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Přerov': {'orp_kod': 7109, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Šternberk': {'orp_kod': 7110, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Šumperk': {'orp_kod': 7111, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Uničov': {'orp_kod': 7112, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Zábřeh': {'orp_kod': 7113, 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	'Bystřice pod Hostýnem': {'orp_kod': 7201, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Holešov': {'orp_kod': 7202, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Kroměříž': {'orp_kod': 7203, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Luhačovice': {'orp_kod': 7204, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Otrokovice': {'orp_kod': 7205, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Rožnov pod Radhoštěm': {'orp_kod': 7206, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Uherské Hradiště': {'orp_kod': 7207, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Uherský Brod': {'orp_kod': 7208, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Valašské Klobouky': {'orp_kod': 7209, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Valašské Meziříčí': {'orp_kod': 7210, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Vizovice': {'orp_kod': 7211, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Vsetín': {'orp_kod': 7212, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Zlín': {'orp_kod': 7213, 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	'Bílovec': {'orp_kod': 8101, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Bohumín': {'orp_kod': 8102, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Bruntál': {'orp_kod': 8103, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Český Těšín': {'orp_kod': 8104, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Frenštát pod Radhoštěm': {'orp_kod': 8105, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Frýdek-Místek': {'orp_kod': 8106, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Frýdlant nad Ostravicí': {'orp_kod': 8107, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Havířov': {'orp_kod': 8108, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Hlučín': {'orp_kod': 8109, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Jablunkov': {'orp_kod': 8110, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Karviná': {'orp_kod': 8111, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Kopřivnice': {'orp_kod': 8112, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Kravaře': {'orp_kod': 8113, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Krnov': {'orp_kod': 8114, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Nový Jičín': {'orp_kod': 8115, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Odry': {'orp_kod': 8116, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Opava': {'orp_kod': 8117, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Orlová': {'orp_kod': 8118, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Ostrava': {'orp_kod': 8119, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Rýmařov': {'orp_kod': 8120, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Třinec': {'orp_kod': 8121, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	'Vítkov': {'orp_kod': 8122, 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
}

