
ORP = {
	1000: {'nazev': 'Praha', 'kraj_kod': 3018, 'kraj_nazev': 'Hlavní město Praha'},
	2101: {'nazev': 'Benešov', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2102: {'nazev': 'Beroun', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2103: {'nazev': 'Brandýs nad Labem-Stará Boleslav', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2104: {'nazev': 'Čáslav', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2105: {'nazev': 'Černošice', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2106: {'nazev': 'Český Brod', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2107: {'nazev': 'Dobříš', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2108: {'nazev': 'Hořovice', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2109: {'nazev': 'Kladno', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2110: {'nazev': 'Kolín', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2111: {'nazev': 'Kralupy nad Vltavou', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2112: {'nazev': 'Kutná Hora', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2113: {'nazev': 'Lysá nad Labem', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2114: {'nazev': 'Mělník', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2115: {'nazev': 'Mladá Boleslav', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2116: {'nazev': 'Mnichovo Hradiště', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2117: {'nazev': 'Neratovice', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2118: {'nazev': 'Nymburk', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2119: {'nazev': 'Poděbrady', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2120: {'nazev': 'Příbram', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2121: {'nazev': 'Rakovník', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2122: {'nazev': 'Říčany', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2123: {'nazev': 'Sedlčany', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2124: {'nazev': 'Slaný', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2125: {'nazev': 'Vlašim', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	2126: {'nazev': 'Votice', 'kraj_kod': 3026, 'kraj_nazev': 'Středočeský kraj'},
	3101: {'nazev': 'Blatná', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3102: {'nazev': 'České Budějovice', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3103: {'nazev': 'Český Krumlov', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3104: {'nazev': 'Dačice', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3105: {'nazev': 'Jindřichův Hradec', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3106: {'nazev': 'Kaplice', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3107: {'nazev': 'Milevsko', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3108: {'nazev': 'Písek', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3109: {'nazev': 'Prachatice', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3110: {'nazev': 'Soběslav', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3111: {'nazev': 'Strakonice', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3112: {'nazev': 'Tábor', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3113: {'nazev': 'Trhové Sviny', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3114: {'nazev': 'Třeboň', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3115: {'nazev': 'Týn nad Vltavou', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3116: {'nazev': 'Vimperk', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3117: {'nazev': 'Vodňany', 'kraj_kod': 3034, 'kraj_nazev': 'Jihočeský kraj'},
	3201: {'nazev': 'Blovice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3202: {'nazev': 'Domažlice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3203: {'nazev': 'Horažďovice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3204: {'nazev': 'Horšovský Týn', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3205: {'nazev': 'Klatovy', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3206: {'nazev': 'Kralovice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3207: {'nazev': 'Nepomuk', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3208: {'nazev': 'Nýřany', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3209: {'nazev': 'Plzeň', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3210: {'nazev': 'Přeštice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3211: {'nazev': 'Rokycany', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3212: {'nazev': 'Stod', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3213: {'nazev': 'Stříbro', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3214: {'nazev': 'Sušice', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	3215: {'nazev': 'Tachov', 'kraj_kod': 3042, 'kraj_nazev': 'Plzeňský kraj'},
	4101: {'nazev': 'Aš', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4102: {'nazev': 'Cheb', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4103: {'nazev': 'Karlovy Vary', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4104: {'nazev': 'Kraslice', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4105: {'nazev': 'Mariánské Lázně', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4106: {'nazev': 'Ostrov', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4107: {'nazev': 'Sokolov', 'kraj_kod': 3051, 'kraj_nazev': 'Karlovarský kraj'},
	4201: {'nazev': 'Bílina', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4202: {'nazev': 'Děčín', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4203: {'nazev': 'Chomutov', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4204: {'nazev': 'Kadaň', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4205: {'nazev': 'Litoměřice', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4206: {'nazev': 'Litvínov', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4207: {'nazev': 'Louny', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4208: {'nazev': 'Lovosice', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4209: {'nazev': 'Most', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4210: {'nazev': 'Podbořany', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4211: {'nazev': 'Roudnice nad Labem', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4212: {'nazev': 'Rumburk', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4213: {'nazev': 'Teplice', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4214: {'nazev': 'Ústí nad Labem', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4215: {'nazev': 'Varnsdorf', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	4216: {'nazev': 'Žatec', 'kraj_kod': 3069, 'kraj_nazev': 'Ústecký kraj'},
	5101: {'nazev': 'Česká Lípa', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5102: {'nazev': 'Frýdlant', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5103: {'nazev': 'Jablonec nad Nisou', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5104: {'nazev': 'Jilemnice', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5105: {'nazev': 'Liberec', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5106: {'nazev': 'Nový Bor', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5107: {'nazev': 'Semily', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5108: {'nazev': 'Tanvald', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5109: {'nazev': 'Turnov', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5110: {'nazev': 'Železný Brod', 'kraj_kod': 3077, 'kraj_nazev': 'Liberecký kraj'},
	5201: {'nazev': 'Broumov', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5202: {'nazev': 'Dobruška', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5203: {'nazev': 'Dvůr Králové nad Labem', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5204: {'nazev': 'Hořice', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5205: {'nazev': 'Hradec Králové', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5206: {'nazev': 'Jaroměř', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5207: {'nazev': 'Jičín', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5208: {'nazev': 'Kostelec nad Orlicí', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5209: {'nazev': 'Náchod', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5210: {'nazev': 'Nová Paka', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5211: {'nazev': 'Nové Město nad Metují', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5212: {'nazev': 'Nový Bydžov', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5213: {'nazev': 'Rychnov nad Kněžnou', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5214: {'nazev': 'Trutnov', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5215: {'nazev': 'Vrchlabí', 'kraj_kod': 3085, 'kraj_nazev': 'Královéhradecký kraj'},
	5301: {'nazev': 'Česká Třebová', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5302: {'nazev': 'Hlinsko', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5303: {'nazev': 'Holice', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5304: {'nazev': 'Chrudim', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5305: {'nazev': 'Králíky', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5306: {'nazev': 'Lanškroun', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5307: {'nazev': 'Litomyšl', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5308: {'nazev': 'Moravská Třebová', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5309: {'nazev': 'Pardubice', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5310: {'nazev': 'Polička', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5311: {'nazev': 'Přelouč', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5312: {'nazev': 'Svitavy', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5313: {'nazev': 'Ústí nad Orlicí', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5314: {'nazev': 'Vysoké Mýto', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	5315: {'nazev': 'Žamberk', 'kraj_kod': 3093, 'kraj_nazev': 'Pardubický kraj'},
	6101: {'nazev': 'Bystřice nad Pernštejnem', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6102: {'nazev': 'Havlíčkův Brod', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6103: {'nazev': 'Humpolec', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6104: {'nazev': 'Chotěboř', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6105: {'nazev': 'Jihlava', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6106: {'nazev': 'Moravské Budějovice', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6107: {'nazev': 'Náměšť nad Oslavou', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6108: {'nazev': 'Nové Město na Moravě', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6109: {'nazev': 'Pacov', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6110: {'nazev': 'Pelhřimov', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6111: {'nazev': 'Světlá nad Sázavou', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6112: {'nazev': 'Telč', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6113: {'nazev': 'Třebíč', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6114: {'nazev': 'Velké Meziříčí', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6115: {'nazev': 'Žďár nad Sázavou', 'kraj_kod': 3107, 'kraj_nazev': 'Kraj Vysočina'},
	6201: {'nazev': 'Blansko', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6202: {'nazev': 'Boskovice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6203: {'nazev': 'Brno', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6204: {'nazev': 'Břeclav', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6205: {'nazev': 'Bučovice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6206: {'nazev': 'Hodonín', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6207: {'nazev': 'Hustopeče', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6208: {'nazev': 'Ivančice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6209: {'nazev': 'Kuřim', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6210: {'nazev': 'Kyjov', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6211: {'nazev': 'Mikulov', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6212: {'nazev': 'Moravský Krumlov', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6213: {'nazev': 'Pohořelice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6214: {'nazev': 'Rosice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6215: {'nazev': 'Slavkov u Brna', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6216: {'nazev': 'Šlapanice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6217: {'nazev': 'Tišnov', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6218: {'nazev': 'Veselí nad Moravou', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6219: {'nazev': 'Vyškov', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6220: {'nazev': 'Znojmo', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	6221: {'nazev': 'Židlochovice', 'kraj_kod': 3115, 'kraj_nazev': 'Jihomoravský kraj'},
	7101: {'nazev': 'Hranice', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7102: {'nazev': 'Jeseník', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7103: {'nazev': 'Konice', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7104: {'nazev': 'Lipník nad Bečvou', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7105: {'nazev': 'Litovel', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7106: {'nazev': 'Mohelnice', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7107: {'nazev': 'Olomouc', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7108: {'nazev': 'Prostějov', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7109: {'nazev': 'Přerov', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7110: {'nazev': 'Šternberk', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7111: {'nazev': 'Šumperk', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7112: {'nazev': 'Uničov', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7113: {'nazev': 'Zábřeh', 'kraj_kod': 3123, 'kraj_nazev': 'Olomoucký kraj'},
	7201: {'nazev': 'Bystřice pod Hostýnem', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7202: {'nazev': 'Holešov', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7203: {'nazev': 'Kroměříž', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7204: {'nazev': 'Luhačovice', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7205: {'nazev': 'Otrokovice', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7206: {'nazev': 'Rožnov pod Radhoštěm', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7207: {'nazev': 'Uherské Hradiště', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7208: {'nazev': 'Uherský Brod', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7209: {'nazev': 'Valašské Klobouky', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7210: {'nazev': 'Valašské Meziříčí', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7211: {'nazev': 'Vizovice', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7212: {'nazev': 'Vsetín', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	7213: {'nazev': 'Zlín', 'kraj_kod': 3131, 'kraj_nazev': 'Zlínský kraj'},
	8101: {'nazev': 'Bílovec', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8102: {'nazev': 'Bohumín', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8103: {'nazev': 'Bruntál', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8104: {'nazev': 'Český Těšín', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8105: {'nazev': 'Frenštát pod Radhoštěm', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8106: {'nazev': 'Frýdek-Místek', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8107: {'nazev': 'Frýdlant nad Ostravicí', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8108: {'nazev': 'Havířov', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8109: {'nazev': 'Hlučín', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8110: {'nazev': 'Jablunkov', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8111: {'nazev': 'Karviná', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8112: {'nazev': 'Kopřivnice', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8113: {'nazev': 'Kravaře', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8114: {'nazev': 'Krnov', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8115: {'nazev': 'Nový Jičín', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8116: {'nazev': 'Odry', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8117: {'nazev': 'Opava', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8118: {'nazev': 'Orlová', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8119: {'nazev': 'Ostrava', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8120: {'nazev': 'Rýmařov', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8121: {'nazev': 'Třinec', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
	8122: {'nazev': 'Vítkov', 'kraj_kod': 3140, 'kraj_nazev': 'Moravskoslezský kraj'},
}
