import openpyxl

from ciselniky import ORP

def get_obyvatelia_orp(DATA_PATH: str) -> list:
    orp = ORP()
    l = []

    #Jihocesky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'jihocesky.xlsx')).active
    cell_range = sheet['D4':'T26']
    for col in range(0,16):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Jihočeský kraj'
        i['kraj_nuts_kod'] = 'CZ031'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n","").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=1
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Jihomoravsky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'jihomoravsky.xlsx')).active
    cell_range = sheet['C4':'W27']
    for col in range(0,21):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Jihomoravský kraj'
        i['kraj_nuts_kod'] = 'CZ064'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Karlovarsky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'karlovarsky.xlsx')).active
    cell_range = sheet['C4':'I27']
    for col in range(0,7):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Karlovarský kraj'
        i['kraj_nuts_kod'] = 'CZ041'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Kralovehradecky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'kralovehradecky.xlsx')).active
    cell_range = sheet['C4':'Q27']
    for col in range(0,15):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Královéhradecký kraj'
        i['kraj_nuts_kod'] = 'CZ052'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Liberecky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'liberecky.xlsx')).active
    cell_range = sheet['C4':'L27']
    for col in range(0,10):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Liberecký kraj'
        i['kraj_nuts_kod'] = 'CZ051'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Moravskoslezsky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'moravskoslezsky.xlsx')).active
    cell_range = sheet['C4':'X27']
    for col in range(0,22):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Moravskoslezský kraj'
        i['kraj_nuts_kod'] = 'CZ080'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Olomoucky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'olomoucky.xlsx')).active
    cell_range = sheet['C4':'O27']
    for col in range(0,13):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Olomoucký kraj'
        i['kraj_nuts_kod'] = 'CZ071'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Pardubicky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'pardubicky.xlsx')).active
    cell_range = sheet['C4':'Q27']
    for col in range(0,15):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Pardubický kraj'
        i['kraj_nuts_kod'] = 'CZ053'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Plzensky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'plzensky.xlsx')).active
    cell_range = sheet['C4':'Q27']
    for col in range(0,15):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Plzeňský kraj'
        i['kraj_nuts_kod'] = 'CZ032'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Praha
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'praha.xlsx')).active
    cell_range = sheet['B4':'B27']
    for col in range(0,1):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Hlavní město Praha'
        i['kraj_nuts_kod'] = 'CZ010'
        i['orp_nazev'] = 'Praha'
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = 0
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value
        l.append(i)

    #Stredocesky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'stredocesky.xlsx')).active
    cell_range = sheet['C6':'AB27']
    for col in range(0,26):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Středočeský kraj'
        i['kraj_nuts_kod'] = 'CZ020'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=1
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value
        l.append(i)

    #Ustecky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'ustecky.xlsx')).active
    cell_range = sheet['C4':'R27']
    for col in range(0,16):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Ústecký kraj'
        i['kraj_nuts_kod'] = 'CZ042'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Vysocina
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'vysocina.xlsx')).active
    cell_range = sheet['C4':'R27']
    for col in range(0,7):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Kraj Vysočina'
        i['kraj_nuts_kod'] = 'CZ063'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)
    for col in range(8,16):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Kraj Vysočina'
        i['kraj_nuts_kod'] = 'CZ063'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    #Zlinsky
    sheet = openpyxl.load_workbook('%s/%s' % (DATA_PATH, 'zlinsky.xlsx')).active
    cell_range = sheet['C4':'O27']
    for col in range(0,13):
        a = 0
        i = {}
        i['kraj_nazev'] = 'Zlínský kraj'
        i['kraj_nuts_kod'] = 'CZ072'
        i['orp_nazev'] = cell_range[a][col].value.replace("- \n", "").replace("-\n", "").replace("\n"," ").replace("  ", " ")
        a+=1
        i['orp_kod'] = orp.get_orp_kod(i.get('orp_nazev'))
        i['celkem'] = cell_range[a][col].value
        a+=2
        i['0'] = cell_range[a][col].value
        a+=1
        i['1-4'] = cell_range[a][col].value
        a+=1
        i['5-9'] = cell_range[a][col].value
        a+=1
        i['10-14'] = cell_range[a][col].value
        a+=1
        i['15-19'] = cell_range[a][col].value
        a+=1
        i['20-24'] = cell_range[a][col].value
        a+=1
        i['25-29'] = cell_range[a][col].value
        a+=1
        i['30-34'] = cell_range[a][col].value
        a+=1
        i['35-39'] = cell_range[a][col].value
        a+=1
        i['40-44'] = cell_range[a][col].value
        a+=1
        i['45-49'] = cell_range[a][col].value
        a+=1
        i['50-54'] = cell_range[a][col].value
        a+=1
        i['55-59'] = cell_range[a][col].value
        a+=1
        i['60-64'] = cell_range[a][col].value
        a+=1
        i['65-69'] = cell_range[a][col].value
        a+=1
        i['70-74'] = cell_range[a][col].value
        a+=1
        i['75-79'] = cell_range[a][col].value
        a+=1
        i['80-84'] = cell_range[a][col].value
        a+=1
        i['85+'] = cell_range[a][col].value + cell_range[a+1][col].value + cell_range[a+2][col].value
        l.append(i)

    return l
